site_name: ELEC 243 Labs
theme: readthedocs
pages:
- Lab Home:
  - {Home: index.md}
  - {Introduction: lab-home/introduction.md}
  - {Lab Station Handbook: lab-home/lab-station-handbook.md}
  - {Tools and Resources: lab-home/tools-and-resources.md}
  - {VirtualBench: lab-home/virtualbench.md}
- References:
  - {Patch Cords and Cables: references/patch-cords-and-cables.md}
  - {The Breadboard: references/breadboard.md}
  - {The Interface Modules: references/interface.md}
  - {Wiring: references/wiring.md}
  - {Resistor Color Codes: references/color_code.md}
  - {Lab Report: references/lab-report.md}
  - {Instruction Manuals and Data Sheets: references/manuals-and-data-sheets.md}
- Lab 1:
  - {Home: lab1/index.md}
  - {Safety: lab1/safety.md}
  - {Background: lab1/background.md}
  - {'DC Measurements: the DMM': lab1/experiment_1-1.md}
  - {Plotting Data in Matlab: lab1/plotting-help.md}
  - {Grounds and Grounding: lab1/interlude.md}
  - {The Oscilloscope and Function Generator: lab1/experiment_1-2.md}
  - {Cleaning Up: lab1/postlude.md}
- Lab 2:
  - {Home: lab2/index.md}
  - {Introduction: lab2/introduction.md}
  - {Before Lab: lab2/before-lab.md}
  - {Measuring Heat and Light: lab2/experiment_2-1.md}
  - {The Breadboard: lab2/breadboard.md}
  - {Electroacoustic Transducers II: lab2/experiment_2-2.md}
  - {Optoelectronic Signal Sources and Sinks: lab2/experiment_2-3.md}
- Lab 3:
  - {Home: lab3/index.md}
  - {Introduction: lab3/introduction.md}
  - {Background: lab3/background.md}
  - {Voltage and Waveform Measurements: lab3/experiment_3-1.md}
  - {Writing a Labview Program: lab3/experiment_3-2.md}
- Lab 4:
  - {Home: lab4/index.md}
  - {Introduction: lab4/introduction.md}
  - {Labview as a Source of Signals: lab4/experiment_4-1.md}
  - {Improved Resistance Measurement: lab4/experiment_4-2.md}
- Lab 5:
  - {Home: lab5/index.md}
  - {Introduction: lab5/introduction.md}
  - {The 741 Op-Amp: lab5/experiment_5-1.md}
  - {Voltage Amplifiers: lab5/experiment_5-2.md}
- Lab 6:
  - {Home: lab6/index.md}
  - {Introduction: lab6/introduction.md}
  - {OpAmp Circuits Part C and D: lab6/experiment_6-1.md}
  - {Transducer Amplifiers: lab6/experiment_6-2.md}

#- Lab 7:
  #- {Home: lab7/index.md}
  #- {Introduction: lab7/introduction.md}
  #- {Digital Logic: lab7/experiment_7-1.md}
#- Lab 8:
  #- {Home: lab8/index.md}
  #- {Introduction: lab8/introduction.md}
  #- {Building a Velleman Kit: lab8/soldering.md}
  #- {Report: lab8/report.md}
  #- {Sign Off Sheet: lab8/sign-off-sheet.md}
#- Final Lab:
  #- {Home: final-lab/index.md}
  #- {Introduction: final-lab/introduction.md}
  #- {Project Specification : final-lab/project-specification.md}
  #- {Deliverables: final-lab/deliverables.md}
- Miscellanous Images:
  - {Home: misc_images/index.md}
docs_dir: ./source
markdown_extensions:
  - pymdownx.arithmatex
  - markdown.extensions.admonition
  - fontawesome_markdown
extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
